import {StyleSheet, Dimensions} from 'react-native';
import colors from './colors';
const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.homeBg,
  },
  container2: {
    flex: 1,
    backgroundColor: colors.passboogBg,
  },
  flex: {
    flex: 1,
  },
  flex2: {
    flex: 2,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ph25: {
    paddingHorizontal: 25,
  },
  headerLeft: {
    height: 20,
    width: 30,
    marginHorizontal: 20,
    marginVertical: 15,
  },
  headerRight: {
    height: 25,
    width: 25,
    marginHorizontal: 20,
    marginVertical: 10,
  },
  curve: {
    position: 'absolute',
    height: '45%',
    width: '100%',
    backgroundColor: colors.secondary,
    borderBottomLeftRadius: width / 3,
    borderBottomRightRadius: width / 3,
    transform: [{scaleX: 1.2}],
  },
  profilePic: {
    height: width / 4,
    width: width / 4,
    borderRadius: width / 8,
    backgroundColor: colors.primary,
    borderWidth: 1,
  },
  optionIcons: {
    height: width / 12,
    width: width / 5,
  },
  optionLabel: {
    color: colors.white,
    textAlign: 'center',
    marginTop: 10,
    fontSize: width / 35,
  },
  optionContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 10,
  },
  name: {
    color: colors.white,
    fontSize: width / 25,
    fontFamily: 'monospace',
  },
  nameContainer: {
    marginLeft: 15,
    marginBottom: 20,
  },
  number: {
    color: colors.white,
    fontSize: width / 25,
    fontFamily: 'monospace',
    letterSpacing: 3,
    marginTop: 5,
  },
  profileContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  firstCardContainer: {
    flex: 3,
    paddingHorizontal: 25,
  },
  firstCard: {
    width: '100%',
    borderRadius: 15,
    overflow: 'hidden',
    height: '100%',
    backgroundColor: colors.white,
    elevation: 1,
  },
  secondCardContainer: {
    flex: 4,
    paddingHorizontal: 25,
    paddingVertical: height / 20,
  },
  secondCard: {
    width: '100%',
    borderRadius: 15,
    overflow: 'hidden',
    height: '100%',
    backgroundColor: colors.white,
    elevation: 1,
  },
  innerCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  markCoin: {
    height: height / 8,
    width: height / 8,
    marginHorizontal: 25,
  },
  redeempoints: {
    fontSize: width / 10,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    color: colors.primary,
  },
  redeemlabels: {
    fontSize: width / 28,
    fontFamily: 'monospace',
    color: 'grey',
  },
  notificationBadgeContainer: {
    position: 'absolute',
    right: 12,
    top: 5,
    borderRadius: 10,
    backgroundColor: 'rgb(237,0,69)',
    height: 20,
    width: 20,
  },
  notificationBadge: {
    color: colors.white,
    textAlign: 'center',
    fontSize: 11,
    textAlignVertical: 'center',
    height: '100%',
  },
  toggler: {
    height: 30,
    width: 30,
    tintColor: colors.primary,
  },
  togglerContainer: {
    position: 'absolute',
    zIndex: 1,
    width: '100%',
  },
  headingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.white,
    paddingVertical: 10,
    paddingHorizontal: 20,
    zIndex: 1,
    height: 60,
    elevation: 3,
  },
  switchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  datepicker: {
    backgroundColor: colors.passboogBg,
    color: 'grey',
    fontSize: width / 27,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'rgb(227,231,238)',
  },
  selectDateRange: {
    color: 'grey',
    fontSize: width / 27,
    fontWeight: '700',
    fontFamily: 'monospace',
    letterSpacing: -0.5,
    flex: 1,
  },
  tabLabel: {
    color: 'grey',
    fontSize: width / 30,
    fontFamily: 'monospace',
    textAlign: 'center',
  },
  bar: {
    height: 4,
    marginTop: 4,
  },
  mt60: {
    marginTop: 60,
  },
  datePickerContainer: {
    backgroundColor: colors.white,
    justifyContent: 'space-around',
    elevation: 3,
  },
  transaction: {
    fontSize: width / 20,
    fontWeight: 'bold',
    flex: 1,
    fontFamily: 'monospace',
    letterSpacing: -0.5,
  },
  scrollItem: {
    height: 100,
    marginTop: 10,
    backgroundColor: colors.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 15,
  },
  scrollItemIcon: {
    height: 70,
    width: 70,
    marginRight: 10,
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  scrollItemTitle: {
    fontSize: width / 26,
    fontFamily: 'monospace',
    letterSpacing: -0.5,
    color: '#00000099',
    marginVertical: 2,
  },
  scrollItemDate: {
    fontSize: width / 32,
    fontFamily: 'monospace',
    letterSpacing: -0.5,
    color: '#00000099',
    marginVertical: 2,
  },
  alignCenter: {
    alignItems: 'center',
    backgroundColor: '#ffffff99',
    position: 'absolute',
    right: 10,
    width: 100,
  },
  textGreen: {
    color: 'green',
  },
  textRed: {
    color: 'red',
  },
  receivedCB: {
    fontSize: width / 20,
    letterSpacing: -0.5,
  },
  CB: {
    fontSize: width / 30,
    letterSpacing: -0.5,
  },
  rupeeContainer: {
    height: width / 15,
    width: width / 15,
    borderRadius: 20,
    backgroundColor: 'green',
    marginRight: 8,
  },
  rupee: {
    textAlign: 'center',
    color: colors.white,
    height: '100%',
    fontSize: width / 22,
    textAlignVertical: 'center',
  },
  amount: {
    fontSize: width / 20,
    fontFamily: 'monospace',
  },
  approved: {
    color: colors.white,
    backgroundColor: 'rgb(30,181,54)',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 30,
    fontSize: width / 35,
    fontFamily: 'monospace',
    marginTop: 15,
  },
  coin: {
    height: 27,
    width: 27,
    borderRadius: 15,
    marginRight: 10,
  },
});

export default styles;
